apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

# customiza o nome e tag da imagem referenciada no deploymnet.yaml
images:
- name: goserver
  newName: lalausan/gitopsfc
  newTag: a9d6b2f3993b2fa2f29c6b439fb88cf2a5a07475
